### ISSUE TITLE
Manage Books Data

### ISSUE THREAD

**Issue by andela-oadesanya** [andela-oadesanya/e-books#2]
- [x] Add a new book (Book Title, URL, Brief Description)
- [x] Update (edit) existing Books
- [x] List Books
- [x] Click on a book to view its details
- [ ] Delete book
- [x] Let Logged in Add Books (sync with the User Management Programmer)
- [ ] Share Book Link with Facebook Friends

**Comment by kelechiodoemelam** [comment]
Hello, Tosin.
I didn't get selected for the fellowship. I was hoping you'd be able to
help me see why. I'd really like to know where I did wrong. It will help me
in the future. Thanks!
Kelechi.
